### ISSUE TITLE
Logo Drafts

### ISSUE THREAD

**Issue by JacksonGartner** [JacksonGartner/essentiacoaching#1]
Rough logo drafts and concepts ready to be presented to client.

Due: Wednesday 20/02/19.

**Comment by jbren48** [comment]
![e concept](https://user-images.githubusercontent.com/36681515/52618627-15d53f80-2eeb-11e9-8d41-4ae60219ba30.jpg)

**Comment by jbren48** [comment]
![concept 2](https://user-images.githubusercontent.com/36681515/52619023-3fdb3180-2eec-11e9-9735-146588278207.jpg)
Concept 2
![concept 3](https://user-images.githubusercontent.com/36681515/52619026-41a4f500-2eec-11e9-95bb-bab145d79ba2.jpg)
Concept 3

**Comment by jbren48** [comment]
![240_f_139698939_5yzb1lzuqngobsahkjqqfftjrdnvgnfc](https://user-images.githubusercontent.com/36681515/52619150-afe9b780-2eec-11e9-99c7-5826fb6ae23c.jpg)
Concept 4
