### ISSUE TITLE
Research Website Ideas

### ISSUE THREAD

**Issue by JacksonGartner** [JacksonGartner/essentiacoaching#4]
Using colour palette and websites sent through by client research design elements for website design.

**Comment by JacksonGartner** [comment]
From client:

https://brettmcfall.com/   I like the opt in box in the top panel; the simplicity; the call to action one very page; the key points in the 6 boxes below the header

https://www.businessandyou.com.au/  i love the simplicity; the header that tells prospects what they will get;  the boxes that outline the strategy

https://conscious.is/ the 'what we do'  page that segments all the services with photos and click through to learn more

https://www.liberatedleaders.com.au/--  clean style; well laid out.

**Comment by jbren48** [comment]
[https://www.arditi.com.au/](url), this sort of look can use any colour palette effectively, Nice and clean but could use a little more features like the "What We Do" and "Prospects" sections from your examples. Plus the interactive banner in a nice feel.

**Comment by JacksonGartner** [comment]
Home, About, Programs, Resources, Client Stories, Contact.
Call now Button (all pages), Contact form (Contact page)
