### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by JacksonGartner** [JacksonGartner/essentiacoaching#9]
Finish Mock-Ups for Home page and 'Further Information pages' then use InVision to design a prototype for the client to use and get a feel for the website design and layout.

Due: Wednesday 13/03/2019

**Comment by jbren48** [comment]
https://invis.io/MUQX2SB7PSC#/351228514_Home_Mockup_V1

**Comment by jbren48** [comment]
Prototype v3 is complete. Implement to Wordpress now.

**Comment by JacksonGartner** [comment]
- Add highlight text above opt-in email box inside the header section.
- Move the 'About Us' section to underneath the header section.
- Use the 6 gold icon section below header as the 'Services' section, move below 'Testimonials' section.
- Use 'Resources' section design as the new 'Client Stories' section.
- Remove right section of 'Contact Us' section, centre contact box and resize and move email / phone to beside the 'send' button and below the contact box.
